<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Adduser extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('user', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'unsigned' => true,
              'length' => 5,
             ),
             'login' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 100,
             ),
             'password' => 
             array(
              'type' => 'string',
              'fixed' => 1,
              'notnull' => true,
              'length' => 40,
             ),
             'salt' => 
             array(
              'type' => 'integer',
              'unsigned' => true,
              'notnull' => true,
              'length' => 2,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('user');
    }
}