<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version4 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('user', 'role', 'enum', '', array(
             'values' => 
             array(
              0 => 'user',
              1 => 'moderator',
              2 => 'administrator',
             ),
             'notnull' => '1',
             'default' => 'user',
             ));
        $this->changeColumn('notification', 'type', 'enum', '', array(
             'values' => 
             array(
              0 => 'user_registration',
             ),
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('user', 'role');
    }
}