<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version8 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('notification', 'type', 'enum', '', array(
             'values' => 
             array(
              0 => 'user_registration',
              1 => 'user_password_reset',
              2 => 'user_new_password_set',
             ),
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->changeColumn('notification', 'type', 'enum', '', array(
             'values' => 
             array(
              0 => 'user_registration',
              1 => 'user_password_reset',
             ),
             'notnull' => '1',
             ));
    }
}