<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version12 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('banking_information', 'banking_information_user_id_user_id', array(
             'name' => 'banking_information_user_id_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'user',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('banking_information', 'banking_information_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('banking_information', 'banking_information_user_id_user_id');
        $this->removeIndex('banking_information', 'banking_information_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
    }
}