<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version11 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('banking_information', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'unsigned' => '1',
              'length' => '5',
             ),
             'bank_name' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '100',
             ),
             'account_number' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '100',
             ),
             'currency' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '100',
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'unsigned' => '1',
              'notnull' => '1',
              'length' => '5',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('banking_information');
    }
}