<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version15 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('auction', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'unsigned' => '1',
              'length' => '5',
             ),
             'title' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '100',
             ),
             'description' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '1000',
             ),
             'number_of_items' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'unsigned' => '1',
              'length' => '5',
             ),
             'start_time' => 
             array(
              'type' => 'timestamp',
              'notnull' => '1',
              'length' => '25',
             ),
             'duration' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => '1',
              1 => '3',
              2 => '7',
              3 => '14',
              4 => '21',
              5 => '30',
              ),
              'notnull' => '1',
              'default' => '7',
              'length' => '',
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'unsigned' => '1',
              'notnull' => '1',
              'length' => '5',
             ),
             'category_id' => 
             array(
              'type' => 'integer',
              'unsigned' => '1',
              'notnull' => '1',
              'length' => '5',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('auction_transaction_type', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'unsigned' => '1',
              'length' => '5',
             ),
             'auction_id' => 
             array(
              'type' => 'integer',
              'unsigned' => '1',
              'notnull' => '1',
              'length' => '5',
             ),
             'transaction_type_id' => 
             array(
              'type' => 'integer',
              'unsigned' => '1',
              'notnull' => '1',
              'length' => '5',
             ),
             'price' => 
             array(
              'type' => 'decimal',
              'scale' => '2',
              'notnull' => '1',
              'length' => '15',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('transaction_type', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'unsigned' => '1',
              'length' => '5',
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'unique' => '1',
              'length' => '100',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('auction');
        $this->dropTable('auction_transaction_type');
        $this->dropTable('transaction_type');
    }
}