<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version21 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('file', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'unsigned' => '1',
              'length' => '5',
             ),
             'filename' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'original_filename' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'mime_type' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '25',
             ),
             'size' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '45',
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'unsigned' => '1',
              'notnull' => '1',
              'length' => '5',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->addColumn('auction', 'thumbnail_file_id', 'integer', '5', array(
             'unsigned' => '1',
             ));
    }

    public function down()
    {
        $this->dropTable('file');
        $this->removeColumn('auction', 'thumbnail_file_id');
    }
}