<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version20 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('auction', 'auction_currency_id_currency_id', array(
             'name' => 'auction_currency_id_currency_id',
             'local' => 'currency_id',
             'foreign' => 'id',
             'foreignTable' => 'currency',
             'onUpdate' => '',
             'onDelete' => 'RESTRICT',
             ));
        $this->addIndex('auction', 'auction_currency_id', array(
             'fields' => 
             array(
              0 => 'currency_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('auction', 'auction_currency_id_currency_id');
        $this->removeIndex('auction', 'auction_currency_id', array(
             'fields' => 
             array(
              0 => 'currency_id',
             ),
             ));
    }
}