<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version19 extends Doctrine_Migration_Base
{
    public function up()
    {
        $currencies = CurrencyTable::getInstance()->findAll();
        if (count($currencies) === 0)
        {
            $currency = new Currency();
            $currency->name = 'PLN';
            $currency->save();
        }
        else
            $currency = $currencies->get(0);
        
        $auctions = AuctionTable::getInstance()->findAll();
        
        foreach ($auctions as $auction)
        {
            $auction->Currency = $currency;
            $auction->save();
        }
            
    }

    public function down()
    {
        
    }
}