<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version24 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('attachment', 'attachment_auction_id_auction_id', array(
             'name' => 'attachment_auction_id_auction_id',
             'local' => 'auction_id',
             'foreign' => 'id',
             'foreignTable' => 'auction',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('attachment', 'attachment_file_id_file_id', array(
             'name' => 'attachment_file_id_file_id',
             'local' => 'file_id',
             'foreign' => 'id',
             'foreignTable' => 'file',
             'onUpdate' => '',
             'onDelete' => 'RESTRICT',
             ));
        $this->addIndex('attachment', 'attachment_auction_id', array(
             'fields' => 
             array(
              0 => 'auction_id',
             ),
             ));
        $this->addIndex('attachment', 'attachment_file_id', array(
             'fields' => 
             array(
              0 => 'file_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('attachment', 'attachment_auction_id_auction_id');
        $this->dropForeignKey('attachment', 'attachment_file_id_file_id');
        $this->removeIndex('attachment', 'attachment_auction_id', array(
             'fields' => 
             array(
              0 => 'auction_id',
             ),
             ));
        $this->removeIndex('attachment', 'attachment_file_id', array(
             'fields' => 
             array(
              0 => 'file_id',
             ),
             ));
    }
}