<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version19 extends Doctrine_Migration_Base
{
    public function up()
    {
        $auctions = AuctionTable::getInstance()->count();
        
        if ($auctions > 0)
        {
            $currencies = CurrencyTable::getInstance()->count();
            if ($currencies === 0)
            {
                Doctrine_Manager::connection()->exec(
                    "INSERT INTO currency (id, name) " .
                    "VALUES ('1', 'PLN')"
                );
            }
            
            Doctrine_Manager::connection()->exec(
                "UPDATE auction SET currency_id = 1 WHERE id > 0"
            );
        }
    }

    public function down()
    {
        
    }
}