<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version22 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('auction', 'auction_thumbnail_file_id_file_id', array(
             'name' => 'auction_thumbnail_file_id_file_id',
             'local' => 'thumbnail_file_id',
             'foreign' => 'id',
             'foreignTable' => 'file',
             'onUpdate' => '',
             'onDelete' => 'RESTRICT',
             ));
        $this->createForeignKey('file', 'file_user_id_user_id', array(
             'name' => 'file_user_id_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'user',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('auction', 'auction_thumbnail_file_id', array(
             'fields' => 
             array(
              0 => 'thumbnail_file_id',
             ),
             ));
        $this->addIndex('file', 'file_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('auction', 'auction_thumbnail_file_id_file_id');
        $this->dropForeignKey('file', 'file_user_id_user_id');
        $this->removeIndex('auction', 'auction_thumbnail_file_id', array(
             'fields' => 
             array(
              0 => 'thumbnail_file_id',
             ),
             ));
        $this->removeIndex('file', 'file_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
    }
}