<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version26 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('delivery', 'delivery_auction_id_auction_id', array(
             'name' => 'delivery_auction_id_auction_id',
             'local' => 'auction_id',
             'foreign' => 'id',
             'foreignTable' => 'auction',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('delivery', 'delivery_delivery_type_id_delivery_type_id', array(
             'name' => 'delivery_delivery_type_id_delivery_type_id',
             'local' => 'delivery_type_id',
             'foreign' => 'id',
             'foreignTable' => 'delivery_type',
             'onUpdate' => '',
             'onDelete' => 'RESTRICT',
             ));
        $this->addIndex('delivery', 'delivery_auction_id', array(
             'fields' => 
             array(
              0 => 'auction_id',
             ),
             ));
        $this->addIndex('delivery', 'delivery_delivery_type_id', array(
             'fields' => 
             array(
              0 => 'delivery_type_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('delivery', 'delivery_auction_id_auction_id');
        $this->dropForeignKey('delivery', 'delivery_delivery_type_id_delivery_type_id');
        $this->removeIndex('delivery', 'delivery_auction_id', array(
             'fields' => 
             array(
              0 => 'auction_id',
             ),
             ));
        $this->removeIndex('delivery', 'delivery_delivery_type_id', array(
             'fields' => 
             array(
              0 => 'delivery_type_id',
             ),
             ));
    }
}