<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version28 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('transaction', 'transaction_user_id_user_id', array(
             'name' => 'transaction_user_id_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'user',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('transaction', 'taai', array(
             'name' => 'taai',
             'local' => 'auction_transaction_type_id',
             'foreign' => 'id',
             'foreignTable' => 'auction_transaction_type',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('transaction', 'transaction_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->addIndex('transaction', 'transaction_auction_transaction_type_id', array(
             'fields' => 
             array(
              0 => 'auction_transaction_type_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('transaction', 'transaction_user_id_user_id');
        $this->dropForeignKey('transaction', 'taai');
        $this->removeIndex('transaction', 'transaction_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->removeIndex('transaction', 'transaction_auction_transaction_type_id', array(
             'fields' => 
             array(
              0 => 'auction_transaction_type_id',
             ),
             ));
    }
}