<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version29 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('auction', 'stage', 'enum', '', array(
             'values' => 
             array(
              0 => 'active',
              1 => 'finished',
             ),
             'notnull' => '1',
             'default' => 'active',
             ));
    }

    public function down()
    {
        $this->removeColumn('auction', 'stage');
    }
}