<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version30 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('notification', 'type', 'enum', '', array(
             'values' => 
             array(
              0 => 'auction_bid_bidder',
              1 => 'auction_bid_auction_owner',
              2 => 'auction_bid_outbidded',
              3 => 'auction_bid_winner',
              4 => 'auction_buy_out_customer',
              5 => 'auction_buy_out_auction_owner',
              6 => 'user_registration',
              7 => 'user_password_reset',
              8 => 'user_new_password_set',
             ),
             'notnull' => '1',
             ));
    }

    public function down()
    {

    }
}