<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version31 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('delivery_form', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'unsigned' => '1',
              'length' => '5',
             ),
             'comment' => 
             array(
              'type' => 'string',
              'length' => '1000',
             ),
             'stage' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'to_fill',
              1 => 'to_process',
              2 => 'processed',
              ),
              'notnull' => '1',
              'default' => 'to_fill',
              'length' => '',
             ),
             'transaction_id' => 
             array(
              'type' => 'integer',
              'unsigned' => '1',
              'notnull' => '1',
              'length' => '5',
             ),
             'address_id' => 
             array(
              'type' => 'integer',
              'unsigned' => '1',
              'length' => '5',
             ),
             'delivery_id' => 
             array(
              'type' => 'integer',
              'unsigned' => '1',
              'length' => '5',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('delivery_form');
    }
}