<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version34 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('news', 'news_user_id_user_id', array(
             'name' => 'news_user_id_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'user',
             'onUpdate' => '',
             'onDelete' => 'RESTRICT',
             ));
        $this->addIndex('news', 'news_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('news', 'news_user_id_user_id');
        $this->removeIndex('news', 'news_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
    }
}