<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
   <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
   <title><?php echo $this->translate('application_name'); ?></title>
   <link rel="stylesheet" type="text/css" media="screen, projection" href="<?php echo $this->baseUrl;?>/css/auctions.css" />
   <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl;?>/css/jquery-ui-1.10.2.custom.css" />
   <script>
       var translate = function(key) {
           var translations = <?php echo json_encode(Helper::getTranslator()->getMessages()); ?>;
           if (translations[key] !== undefined) {
               return translations[key];
           }
           return key;
       };
       
       var getEnum = function(key) {
           var fieldIdEnums = <?php echo json_encode(FieldIdEnum::getEnums()); ?>;
           var paramIdEnums = <?php echo json_encode(ParamIdEnum::getEnums()); ?>;
           
           return fieldIdEnums[key] || paramIdEnums[key] || key;
       };
   </script>
   <script src="<?php echo $this->baseUrl;?>/js/jquery-1.9.1.js" type="text/javascript"></script>
   <script src="<?php echo $this->baseUrl;?>/js/jquery-ui-1.10.2.custom.js" type="text/javascript"></script>
   <script src="<?php echo $this->baseUrl;?>/js/auctions.js" type="text/javascript"></script>
</head>
<body>
    <div id="page">
	<div id="header">
            <div id="banner">
                <a href="<?= $this->baseUrl()?>"><img src="<?= $this->baseUrl() ?>/img/logo.png" /></a>
            </div>
            <div id="menuBar">
                <div id="menuBarLeft">
                    <?php
                        $menu = new Menu();
                        $menu
                            ->addElement(
                                    'login',
                                    Menu_Element::create('login', 'login', 'menu-log_in')
                                        ->enableFor(Enum_Acl_Role::GUEST)
                            )
                            ->addElement(
                                    'registration',
                                    Menu_Element::create('registration', 'registrationForm', 'menu-registration')
                                        ->enableFor(Enum_Acl_Role::GUEST)
                            )
                            ->addElement(
                                    'userPanel',
                                    Menu_Element::create('user/panel', 'userPanel', 'menu-user_panel')
                                        ->enableFor(Enum_Acl_Role::ADMINISTRATOR)
                                        ->enableFor(Enum_Acl_Role::MODERATOR)
                                        ->enableFor(Enum_Acl_Role::USER)
                            )
                            ->addElement(
                                    'administrator',
                                    Menu_Element::create('administrator', 'administrator', 'menu-administrator')
                                        ->enableFor(Enum_Acl_Role::ADMINISTRATOR)
                            )
                            ->addElement(
                                    'logout',
                                    Menu_Element::create('auth/logout', 'logout', 'menu-log_out')
                                        ->enableFor(Enum_Acl_Role::ADMINISTRATOR)
                                        ->enableFor(Enum_Acl_Role::MODERATOR)
                                        ->enableFor(Enum_Acl_Role::USER)
                            );

                        $firstElement = true;
                        foreach ($menu as $menuElement)
                        {
                            if ($firstElement)
                                $firstElement = false;
                            else
                                echo $this->translate('menu-spearator');

                            $class = $menuElement->isActive() ? "class='menuActive'" : "";

                            echo "<a href='" . $this->baseUrl() . '/' . $menuElement->getRoute() . "' " . $class . ">" . $menuElement->getDescription() . "</a> ";
                        }
                    ?>
                </div>
                <div id="menuBarRight">
                    <?php if (Zend_Auth::getInstance()->hasIdentity()) : ?>
                        <a href="<?=$this->baseUrl();?>/user/panel"><?= Auth_User::getInstance()->getUser()->login; ?></a>
                    <?php else : ?>
                        &nbsp;
                    <?php endif; ?>
                </div>
            </div>
	</div>
	<div id="middle">
                <?php echo $this->layout()->content; ?>
	</div>
    </div>
    <div id="footer">
        <p>Copyright &copy; 2013</p>
    </div>
</body>
</html>