<?php

/**
 * BaseAuctionTransactionType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $auction_id
 * @property integer $transaction_type_id
 * @property decimal $price
 * @property TransactionType $TransactionType
 * @property Auction $Auction
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseAuctionTransactionType extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('auction_transaction_type');
        $this->hasColumn('id', 'integer', 5, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'unsigned' => true,
             'length' => '5',
             ));
        $this->hasColumn('auction_id', 'integer', 5, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => '5',
             ));
        $this->hasColumn('transaction_type_id', 'integer', 5, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => '5',
             ));
        $this->hasColumn('price', 'decimal', 15, array(
             'type' => 'decimal',
             'scale' => 2,
             'notnull' => true,
             'length' => '15',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TransactionType', array(
             'local' => 'transaction_type_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('Auction', array(
             'local' => 'auction_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}