<?php

/**
 * BaseTransaction
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property integer $auction_transaction_type_id
 * @property decimal $price
 * @property integer $number_of_items
 * @property User $User
 * @property AuctionTransactionType $AuctionTransactionType
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseTransaction extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('transaction');
        $this->hasColumn('id', 'integer', 5, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'unsigned' => true,
             'length' => '5',
             ));
        $this->hasColumn('user_id', 'integer', 5, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => '5',
             ));
        $this->hasColumn('auction_transaction_type_id', 'integer', 5, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => '5',
             ));
        $this->hasColumn('price', 'decimal', 15, array(
             'type' => 'decimal',
             'scale' => 2,
             'notnull' => true,
             'length' => '15',
             ));
        $this->hasColumn('number_of_items', 'integer', 5, array(
             'type' => 'integer',
             'notnull' => true,
             'unsigned' => true,
             'length' => '5',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('AuctionTransactionType', array(
             'local' => 'auction_transaction_type_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}