<?php

/**
 * BaseDeliveryType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property boolean $cash_on_delivery
 * @property Doctrine_Collection $DeliveriyTypes
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseDeliveryType extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('delivery_type');
        $this->hasColumn('id', 'integer', 5, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'unsigned' => true,
             'length' => '5',
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '100',
             ));
        $this->hasColumn('cash_on_delivery', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));


        $this->index('delivery_type_unique', array(
             'fields' => 
             array(
              0 => 'name',
              1 => 'cash_on_delivery',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Delivery as DeliveriyTypes', array(
             'local' => 'id',
             'foreign' => 'delivery_type_id'));
    }
}