<?php

/**
 * BaseAuction
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property string $description
 * @property integer $number_of_items
 * @property timestamp $start_time
 * @property enum $duration
 * @property integer $user_id
 * @property integer $category_id
 * @property integer $currency_id
 * @property User $User
 * @property Category $Category
 * @property Currency $Currency
 * @property Doctrine_Collection $AuctionTransactionTypes
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseAuction extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('auction');
        $this->hasColumn('id', 'integer', 5, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'unsigned' => true,
             'length' => '5',
             ));
        $this->hasColumn('title', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '100',
             ));
        $this->hasColumn('description', 'string', 1000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '1000',
             ));
        $this->hasColumn('number_of_items', 'integer', 5, array(
             'type' => 'integer',
             'notnull' => true,
             'unsigned' => true,
             'length' => '5',
             ));
        $this->hasColumn('start_time', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('duration', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 1,
              1 => 3,
              2 => 7,
              3 => 14,
              4 => 21,
              5 => 30,
             ),
             'notnull' => true,
             'default' => 7,
             ));
        $this->hasColumn('user_id', 'integer', 5, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => '5',
             ));
        $this->hasColumn('category_id', 'integer', 5, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => '5',
             ));
        $this->hasColumn('currency_id', 'integer', 5, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => '5',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Category', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('Currency', array(
             'local' => 'currency_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasMany('AuctionTransactionType as AuctionTransactionTypes', array(
             'local' => 'id',
             'foreign' => 'auction_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}