<?php

/**
 * BaseDeliveryForm
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $comment
 * @property enum $stage
 * @property integer $transaction_id
 * @property integer $address_id
 * @property integer $delivery_id
 * @property Transaction $Transaction
 * @property Address $Address
 * @property Delivery $Delivery
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseDeliveryForm extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('delivery_form');
        $this->hasColumn('id', 'integer', 5, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'unsigned' => true,
             'length' => '5',
             ));
        $this->hasColumn('comment', 'string', 1000, array(
             'type' => 'string',
             'length' => '1000',
             ));
        $this->hasColumn('stage', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'to_fill',
              1 => 'to_process',
              2 => 'processed',
             ),
             'notnull' => true,
             'default' => 'to_fill',
             ));
        $this->hasColumn('transaction_id', 'integer', 5, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => '5',
             ));
        $this->hasColumn('address_id', 'integer', 5, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => '5',
             ));
        $this->hasColumn('delivery_id', 'integer', 5, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => '5',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Transaction', array(
             'local' => 'transaction_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('Address', array(
             'local' => 'address_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('Delivery', array(
             'local' => 'delivery_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));
    }
}