<?php

/**
 * BaseDelivery
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $auction_id
 * @property integer $delivery_type_id
 * @property decimal $price
 * @property Auction $Auction
 * @property DeliveryType $DeliveryType
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseDelivery extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('delivery');
        $this->hasColumn('id', 'integer', 5, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'unsigned' => true,
             'length' => '5',
             ));
        $this->hasColumn('auction_id', 'integer', 5, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => '5',
             ));
        $this->hasColumn('delivery_type_id', 'integer', 5, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => '5',
             ));
        $this->hasColumn('price', 'decimal', 15, array(
             'type' => 'decimal',
             'scale' => 2,
             'notnull' => true,
             'length' => '15',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Auction', array(
             'local' => 'auction_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('DeliveryType', array(
             'local' => 'delivery_type_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));
    }
}