<div id="container">
    <div id="contentWithoutSubMenu">
        <?php echo $this->form; ?>
        <div class="loginPageCustoms">
            <a href="<?=$this->baseUrl;?>user/password-reset-request"><?= $this->translate('caption-password_reset'); ?></a><br/>
            <a href="<?=$this->baseUrl;?>user/registration"><?= $this->translate('caption-login_page_registration_link'); ?></a>
        </div>
    </div>
</div>