<?php
    $menu = new Menu();
    $menu
        ->addElement(
                'changePassword',
                Menu_Element::create('/category/show-administrator-list', 'categoryShowAdministratorList', 'submenu-categories_list')
                    ->enableFor(Enum_Acl_Role::ADMINISTRATOR)
        );

    foreach ($menu as $menuElement)
        echo "<a href='" . $this->baseUrl() . '/' . $menuElement->getRoute() . "'>" . $menuElement->getDescription() . "</a> <BR/>";
?>