<div class="subMenu">
<?php
    $menu = new Menu();
    $menu
        ->addElement(
                'changePassword',
                Menu_Element::create('category/show-administrator-list', 'categoryShowAdministratorList', 'submenu-categories_list')
                    ->enableFor(Enum_Acl_Role::ADMINISTRATOR)
        );

    foreach ($menu as $menuElement)
    {
        $class = $menuElement->isActive() ? "class='menuActive'" : "";
        
        echo "<a href='" . $this->baseUrl() . '/' . $menuElement->getRoute() . "' " . $class . ">" . $menuElement->getDescription() . "</a> <BR/>";
    }
?>
</div>