<div id="container">
    <div id="contentWithoutSubMenu">
        <div id="auction">
            <div id="header">
                <div id="thumbnailContainer">
                    <?php if (!empty($this->auction->File->filename)) : ?>
                    <img src="<?php echo $this->baseUrl() . '/../uploads/' . $this->auction->File->filename;?>" id="thumbnail"/>
                    <?php endif; ?>
                </div>
                <div id="titleContainer">
                    <div id="title">
                        <a href="<?=$this->baseUrl('auction/show/' . $this->auction->id)?>"><?=$this->auction->title?></a>
                    </div>

                    <div id="categoryList">
                        <?php
                        for ($i = count($this->categoriesCollection); $i > 0; $i--) :
                            $category = $this->categoriesCollection->get($i - 1);
                            ?>
                            <a href="<?=$this->baseUrl('auction/show-list-for-category/' . $category->id)?>"><?=$category->name?></a>
                            <?php
                            if ($i > 1)
                                echo " > ";
                        endfor;
                        ?>
                    </div>
                </div>
                <div id="timeAndUserInformation">
                    <?php echo $this->translate('label-auction_start_time') . " <strong>" . $this->auction->start_time . "</strong>"?><br/>
                    <?php echo $this->translate('label-auction_end_time') . " <strong>" . $this->auction->getEndTime() . "</strong>"?><br/>
                    <?php echo $this->translate('label-auction_seller') . " <strong><a href='" . $this->baseUrl('user/show/' . $this->auction->User->id) . "'>" . $this->auction->User->login . "</a></strong>"?><br/>
                    <?php echo $this->translate('label-auction_number_of_items') . " <strong>" . $this->numberOfItemsLeft . "</strong>/" . $this->auction->number_of_items ;?><br/>
                </div>
            </div>
            <div id="description">
                <?=$this->form?>
            </div>
        </div>
    </div>
</div>