<?php

/**
 * Address
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Address extends BaseAddress
{

    /**
     * Get one line information from Address
     * 
     * @return String
     */
    public function getOneLineInfo()
    {
        return 
            $this->name . " " . 
            $this->surname . ", " .
            $this->street . ", " . 
            $this->postal_code . " " . 
            $this->city;
    }
}