<?php

/**
 * BankingInformationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BankingInformationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BankingInformationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BankingInformation');
    }
}