<?php

/**
 * DeliveryFormTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DeliveryFormTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DeliveryFormTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DeliveryForm');
    }
    
    /**
     * Returns forms for specified user and stage.
     * 
     * @param User $user
     * @param Enum_Db_DeliveryForm_Stage $stage
     * @return Doctrine_Collection
     */
    public function getFormsForUserAndStage(User $user, $stage)
    {
        return $this->createQuery()
                ->where('DeliveryForm.Transaction.AuctionTransactionType.Auction.user_id = ?', $user->id)
                ->addWhere('stage = ?', $stage)
                ->execute();
    }
}