<?php

/**
 * DeliveryFormTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DeliveryFormTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DeliveryFormTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DeliveryForm');
    }
}