<?php

/**
 * DeliveryTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DeliveryTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DeliveryTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DeliveryType');
    }
    
    public function isUnique($name, $cashOnDelivery, $id)
    {
        $query = $this->createQuery()
                ->where("name = ?", $name)
                ->addWhere("cash_on_delivery = ?", $cashOnDelivery);
        
        if (!is_null($id))
            $query->addWhere('id != ?', $id);
        
        return $query->count() === 0;
    }
}