<?php

/**
 * DeliveryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DeliveryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DeliveryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Delivery');
    }
}