<?php

/**
 * File
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class File extends BaseFile
{

    /**
     * Returns path to file on server
     * 
     * @return String
     */
    public function getPath()
    {
        return Zend_Controller_Front::getInstance()->getBaseUrl() . '/../uploads/' . $this->filename;
    }
    
}