<?php

/**
 * User
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class User extends BaseUser
{
    
    /**
     * 
     * @param string $password
     * @return boolean
     */
    public function checkPassword($password)
    {
        return $this->password === sha1($this->salt . $password);
    }
    
    /**
     * 
     * @return User
     */
    public function updateLastLogin()
    {
        $this->last_login = Zend_Date::now()->toString();
        $this->save();
        
        return $this;
    }
}