
<div id="container">
    <div id="contentWithoutSubMenu">
        <?= View_Helper::getErrorMessage($this->message); ?>
        <?php echo $this->addForm; ?>
    </div>
</div>

<script>
    var deliveryTypeIds = <?php echo json_encode(DeliveryTypeTable::getInstance()->getIds()); ?>;
    var fileIds = [1, 2, 3, 4, 5];
</script>
<script src="<?php echo $this->baseUrl();?>/js/auction/add.js" type="text/javascript"></script>