<div id="container">
    <div id="contentWithoutSubMenu">
        <div id="auction">
            <div id="header">
                <div id="thumbnailContainer">
                    <?php if (!empty($this->auction->File->filename)) : ?>
                    <img src="<?php echo $this->baseUrl() . '/../uploads/' . $this->auction->File->filename;?>" id="thumbnail"/>
                    <?php endif; ?>
                </div>
                <div id="titleContainer">
                    <div id="title">
                        <?=$this->auction->title?>
                    </div>

                    <div id="categoryList">
                        <?php
                        for ($i = count($this->categoriesCollection); $i > 0; $i--) :
                            $category = $this->categoriesCollection->get($i - 1);
                            ?>
                            <a href="<?=$this->baseUrl('auction/show-list-for-category/' . $category->id)?>"><?=$category->name?></a>
                            <?php
                            if ($i > 1)
                                echo " > ";
                        endfor;
                        ?>
                    </div>
                </div>
                <div id="timeAndUserInformation">
                    <?php echo $this->translate('label-auction_start_time') . " <strong>" . $this->auction->start_time . "</strong>"?><br/>
                    <?php echo $this->translate('label-auction_end_time') . " <strong>" . $this->auction->getEndTime() . "</strong>"?><br/>
                    <?php echo $this->translate('label-auction_seller') . " <strong><a href='" . $this->baseUrl('user/' . $this->auction->User->id) . "'>" . $this->auction->User->login . "</a></strong>"?><br/>
                    <?php echo $this->translate('label-auction_number_of_items') . " <strong>" . $this->numberOfItemsLeft . "</strong>/" . $this->auction->number_of_items ;?><br/>
                </div>
            </div>
            <?php if (count($this->auction->Attachments) > 0) : ?>
                <div id="gallery">
                    <?php 
                    foreach ($this->auction->Attachments as $attachment) :
                        ?>
                    <a href="<?php echo $attachment->File->getPath();?>" rel="prettyPhoto[gallery]"><img src="<?php echo $attachment->File->getPath();?>" class="attachment"/></a> 
                        <?php
                    endforeach;
                    ?>
                </div>
            <?php endif;?>
            <?php if ($this->numberOfItemsLeft > 0 && $this->auction->stage !== Enum_Db_Auction_Stage::FINISHED) : ?>
                <div id="transaction">
                    <?php 
                        if ($this->isBiddingOnly ^ $this->isBuyOutOnly) : ?>
                            <div id="oneType">
                                <?php if ($this->isBiddingOnly) : ?>
                                    <?= Auction_ViewHelper::getTransactionDiv($this->auctionTransactionTypes->get(0)) ?>
                                <?php else : ?>
                                    <?= Auction_ViewHelper::getTransactionDiv($this->auctionTransactionTypes->get(0)) ?>
                                <?php endif;?>
                            </div>
                        <?php else : ?>
                            <div id="twoTypes">
                                    <?= Auction_ViewHelper::getTransactionDiv($this->auctionTransactionTypes->get(0)) ?>
                                    <?= Auction_ViewHelper::getTransactionDiv($this->auctionTransactionTypes->get(1)) ?>
                            </div>
                        <?php endif; ?>
                </div>
            <?php endif; ?>
            <div id="description">
                <?=$this->auction->description?>
            </div>
            <div id="transactions">
                <?php if ($this->isBiddingOnly || $this->auctionTransactionTypesCount === 2) : 
                    $biddings = $this->auctionTransactionTypes->get(0)->getItemsToShow(); 
                    if (count($biddings[ParamIdEnum::TRANSACTION_VALID]) > 0 || count($biddings[ParamIdEnum::TRANSACTION_INVALID]) > 0) : ?>
                        <table class="auctionsTable">
                            <tr>
                                <th>
                                    <?= $this->translate('label-login'); ?>
                                </th>
                                <th>
                                    <?= $this->translate('label-auction_number_of_items'); ?>
                                </th>
                                <th>
                                    <?= $this->translate('label-price'); ?>
                                </th>
                                <th>
                                    <?= $this->translate('label-date'); ?>
                                </th>
                            </tr>
                            <?php foreach ($biddings[ParamIdEnum::TRANSACTION_VALID] as $validTransaction) : ?>
                                <tr class="importantRow">
                                    <td>
                                        <?php echo "<a href='" . $this->baseUrl('user/' . $validTransaction->User->id) . "'>" . $validTransaction->User->login . "</a>"; ?>
                                    </td>
                                    <td>
                                        <?= $validTransaction->number_of_items ?>
                                    </td>
                                    <td>
                                        <?= Formatter_Price::formatWithCurrency($validTransaction->price, $this->auction->Currency->name); ?>
                                    </td>
                                    <td>
                                        <?= $validTransaction->created_at ?>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                            <?php foreach ($biddings[ParamIdEnum::TRANSACTION_INVALID] as $validTransaction) : ?>
                                <tr>
                                    <td>
                                        <?php echo "<a href='" . $this->baseUrl('user/' . $validTransaction->User->id) . "'>" . $validTransaction->User->login . "</a>"; ?>
                                    </td>
                                    <td>
                                        <?= $validTransaction->number_of_items ?>
                                    </td>
                                    <td>
                                        <?= Formatter_Price::formatWithCurrency($validTransaction->price, $this->auction->Currency->name); ?>
                                    </td>
                                    <td>
                                        <?= $validTransaction->created_at ?>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        </table>
                    <?php else : ?>
                        <strong><?= $this->translate('message-transaction_no_biddings'); ?></strong><br/>
                    <?php endif; ?>
                <?php endif; ?>
                <br/>
                <?php if ($this->isBuyOutOnly || $this->auctionTransactionTypesCount === 2) :
                    $buyOuts = $this->auctionTransactionTypes->get($this->isBuyOutOnly ? 0 : 1)->getItemsToShow();
                    if (count($buyOuts) > 0) : ?>
                        <table class="auctionsTable">
                            <tr>
                                <th>
                                    <?= $this->translate('label-login'); ?>
                                </th>
                                <th>
                                    <?= $this->translate('label-auction_number_of_items'); ?>
                                </th>
                                <th>
                                    <?= $this->translate('label-price'); ?>
                                </th>
                                <th>
                                    <?= $this->translate('label-date'); ?>
                                </th>
                            </tr>
                            <?php foreach ($buyOuts as $validTransaction) : ?>
                                <tr class="importantRow">
                                    <td>
                                        <?php echo "<a href='" . $this->baseUrl('user/' . $validTransaction->User->id) . "'>" . $validTransaction->User->login . "</a>"; ?>
                                    </td>
                                    <td>
                                        <?= $validTransaction->number_of_items ?>
                                    </td>
                                    <td>
                                        <?= Formatter_Price::formatWithCurrency($validTransaction->price, $this->auction->Currency->name); ?>
                                    </td>
                                    <td>
                                        <?= $validTransaction->created_at ?>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        </table>
                    <?php else : ?>
                        <strong><?= $this->translate('message-transaction_no_buy_outs'); ?></strong><br/>
                    <?php endif; ?>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>

<script src="<?php echo $this->baseUrl();?>/js/auction/show.js" type="text/javascript"></script>