<div id="container">
    <div id="content">
        <?php foreach ($this->newses as $news) : ?>
        <div class="news">
            <fieldset>
                <legend><?php echo $news->title; ?></legend>
                <div class="content">
                    <?php echo $news->description; ?>
                    <div class="autor">
                        <?=$news->created_at?> <a href="<?=$this->baseUrl('/user/show/' . $news->User->id)?>"><?php echo $news->User->login; ?></a>
                    </div>
                </div>
            </fieldset>
        </div>
        <?php endforeach; ?>
    </div>
</div>
<div id="subMenu">
    <?php
    $categories = CategoryTable::getInstance()->getMainCategories();
    
    foreach ($categories as $category)
        echo "<a href=" . $this->baseUrl() . "/auction/show-list-for-category/" . $category->id . ">" . $category->name . "</a><br/>";
    ?>
</div>