<div id="container">
    <div id="content">
        <?= View_Helper::getErrorMessage($this->message); ?>
        <table>
            <tr>
                <th>
                    <?=$this->translate('label-category_name')?>
                </th>
                <th>
                    <?=$this->translate('label-category_description')?>
                </th>
                <th>
                </th>
            </tr>
            <?php foreach ($this->mainCategories as $category) : ?>
            <tr>
                <td>
                    <?=$category[FieldIdEnum::CATEGORY_NAME]?>
                </th>
                <td>
                    <?=$category[FieldIdEnum::CATEGORY_DESCRIPTION]?>
                </td>
                <td class="textCenter">
                    <a href="<?=$this->baseUrl();?>/category/edit/<?=$category[FieldIdEnum::CATEGORY_ID]?>" class="editButton" title="<?=$this->translate('caption-edit')?>"></a>
                    <a href="#" class="deleteButton" onclick="confirmationBox('<?=$this->baseUrl();?>/category/delete/<?=$category[FieldIdEnum::CATEGORY_ID]?>');" title="<?=$this->translate('caption-delete')?>"></a>
                </td>
            </tr>
            <?php    endforeach; ?>
        </table>
        <br/>
        <a class="addButton" href="<?=$this->baseUrl();?>/category/add"></a><br/>
    </div>
</div>
<?php echo $this->render('administrator/sub-menu.phtml') ?>

<div id="dialog-box" title="<?= $this->translate('title-delete_category');?>">
  <p>
      <span class="ui-icon ui-icon-alert" style="float: left; margin: 0 7px 20px 0;"></span>
      <?= $this->translate('message-delete_category_confirmation'); ?>
  </p>
</div>